// ru-code (extended-view redesign, ADVERSARY seat): HOSTILE DATA through the real app. The
// fixture `fixtures/sessions/hostile-6c096be2/session.jsonl` is 6c096be2 with three mutations
// (generated by the adversary seat, adversary-report.md): the agent type `Explore` → a 147-char
// name with no spaces (a hostile agent definition), the description «Discover project
// structure» → a 174-char RTL string with digits, and one GHOST notification (`taskId:
// ghost-00000000`, no launch anywhere). H1: switch to the extended view first.
//
//   ADV-E7  cards with a long type / RTL description stay inside their row; the status chip
//           stays inside the card; the ghost notification is still a row (zero-drop, A3)
import * as NodePath from "node:path";

import { expect, test } from "./fixtures.ts";
import type { RealSessionFixture } from "../harness/realSessions.ts";
import {
  TIMELINE,
  expectExtendedMounted,
  openFreshDraft,
  replaySession,
  scrollTo,
  scrollUntilVisible,
  switchToExtended,
  waitForTimelineQuiet,
} from "./extendedView.ts";

const HOSTILE: RealSessionFixture = {
  id: "hostile-6c096be2",
  file: NodePath.resolve(
    import.meta.dirname,
    "../fixtures/sessions/hostile-6c096be2/session.jsonl",
  ),
  // No agent tree on purpose (the mutated ids match no sidecar) — the cards read the file only.
  subagentsDir: NodePath.resolve(import.meta.dirname, "../fixtures/sessions/hostile-6c096be2/none"),
  firstUser: "run some agentic flow",
  records: 131,
  humanTurns: 7,
  agentLaunches: 6,
};

const consoleLines: string[] = [];
test.beforeEach(({ page }) => {
  consoleLines.length = 0;
  page.on("pageerror", (error) => consoleLines.push(`[pageerror] ${error.message}`));
});
test.afterEach(() => {
  expect(consoleLines.filter((line) => line.startsWith("[pageerror]"))).toEqual([]);
});

test("ADV-E7: hostile strings — long agent type / RTL description stay inside the card, the chip stays inside, the ghost notification is a row", async ({
  page,
}) => {
  // Attacks: AgentCards.tsx line 1 (`shrink-0 font-medium` on the NAME — a long type cannot
  // shrink, so it pushes the status chip / duration past the card's right edge; only the
  // description is `min-w-0 truncate`), and the zero-drop promise (A3) for a notification that
  // matches no launch (`isAgentNotification` → agent-marker with no entity, or a notice row).
  // Does NOT prove: pixel-perfect RTL bidi rendering — only containment.
  test.setTimeout(150_000);
  await openFreshDraft(page);
  await switchToExtended(page);
  await replaySession(page, HOSTILE, { pacing: { kind: "instant" }, mirrorRegistry: false });
  await expectExtendedMounted(page);
  const timeline = page.locator(TIMELINE);
  await scrollTo(page, 0);
  const fleet = timeline.locator("[data-agent-fleet]").first();
  await expect(fleet).toBeVisible();
  if ((await fleet.getAttribute("aria-expanded")) !== "true") {
    await fleet.click();
    await waitForTimelineQuiet(page);
  }
  const cards = timeline.locator("[data-agent-card]");
  await expect(cards.first()).toBeVisible();
  const failures = await page.evaluate((timelineSelector) => {
    const root = document.querySelector(timelineSelector)!;
    const hits: string[] = [];
    for (const card of root.querySelectorAll<HTMLElement>("[data-agent-card]")) {
      const cardBox = card.getBoundingClientRect();
      if (cardBox.height === 0) continue;
      const shell = card.closest<HTMLElement>(".max-w-3xl");
      const shellBox = shell?.getBoundingClientRect();
      const id = card.getAttribute("data-agent-card")!;
      if (shellBox !== undefined && cardBox.right > shellBox.right + 0.5) {
        hits.push(
          `${id}: card right ${Math.round(cardBox.right)} > row right ${Math.round(shellBox.right)}`,
        );
      }
      const chip = card.querySelector<HTMLElement>("[data-agent-status]");
      if (chip === null) {
        hits.push(`${id}: no status chip`);
        continue;
      }
      const chipBox = chip.getBoundingClientRect();
      if (chipBox.right > cardBox.right + 0.5 || chipBox.left < cardBox.left - 0.5) {
        hits.push(
          `${id}: status chip [${Math.round(chipBox.left)}, ${Math.round(chipBox.right)}] outside the card [${Math.round(cardBox.left)}, ${Math.round(cardBox.right)}]`,
        );
      }
      for (const span of card.querySelectorAll<HTMLElement>("span")) {
        const box = span.getBoundingClientRect();
        if (box.width > 0 && box.right > cardBox.right + 0.5) {
          hits.push(
            `${id}: text «${(span.textContent ?? "").trim().slice(0, 24)}…» right ${Math.round(box.right)} > card right ${Math.round(cardBox.right)}`,
          );
          break;
        }
      }
    }
    return hits;
  }, TIMELINE);
  // The ghost notification (no launch matches `ghost-00000000`) is still a ROW — never dropped.
  const ghost = timeline.getByText(/never launched here/);
  const ghostVisible = await scrollUntilVisible(page, ghost);
  console.log(
    `[ADV-E7] ghost notification rendered as a row: ${ghostVisible}; layout failures: ${failures.length}`,
  );
  if (!ghostVisible)
    failures.push("ghost notification (unknown task id) is not a row — zero-drop broken");
  expect(failures, failures.join("\n")).toEqual([]);
});
