// ru-code S111 — what the host checks on what a plugin hands it, in a real browser.
//
// THE CLAIM. Every check the web host applies guards something REAL (owner, S111): a string the
// host draws is refused only when it is NOT a string, because the draw sites already truncate it;
// a panel id is judged by ONE rule. Three things the old rules refused, drawn:
//
//   · #2 — a page and a panel whose TITLE is 100 characters are kept: the page's footer entry
//     navigates and its header draws the whole title, truncated by CSS; the panel's footer button
//     carries the title (`SidebarChrome.tsx` labels a global panel's button with it);
//   · #1 — a global-slot panel whose id starts with a digit (`2fa`) is shown and opens: the seam
//     kept it, the slot's own second pattern used to drop it silently (S110 R04);
//   · #8 — a toast whose detail has a newline is SHOWN, with both lines.
//
// WHY A GENERATED FIXTURE. No shipped plugin sits on these edges (and their product code is not
// ours to change), so the plugin whose whole point is to sit on them is written here — like
// `panelDescription.e2e.test.ts`'s — and removed after the file.
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";

import { expect, openChat, state, test, type Page } from "./fixtures.ts";
import {
  removePluginFolder,
  restartPluginsApp,
  stopPluginsApp,
  type PluginsHarnessState,
} from "../harness/pluginsBoot.ts";
import { saveEvidenceScreenshot } from "../harness/pluginsEvidence.ts";

const RULES_ID = "host-rules";
/** 100 characters each — over the old 64-char cap, which cost the whole page or panel. */
const PAGE_TITLE =
  "A page title of exactly one hundred characters, drawn by the host and truncated by its own CSS rules";
const PANEL_TITLE =
  "A panel title of exactly one hundred characters, labelling its footer button and its slot heading!!!";
const TOAST_TITLE = "S111 multi-line toast";
const TOAST_DETAIL = "first line of the detail\nsecond line of the detail";

const RULES_MANIFEST = {
  id: RULES_ID,
  name: "Host Rules",
  version: "0.1.0",
  apiVersion: 2,
  web: "web/index.mjs",
};

const RULES_WEB_ENTRY = `// e2e fixture (generated by hostRules.e2e.test.ts): the host's checks at their S111 edges.
import { createElement } from "react";

let ctxRef = null;
const remember = (ctx) => {
  ctxRef = ctx;
  return ctx;
};

const WidePage = () => createElement("div", { "data-testid": "host-rules-page" }, "wide page");
const TwoFactor = () =>
  createElement(
    "button",
    {
      type: "button",
      "data-testid": "host-rules-toast",
      onClick: () => ctxRef?.toast("info", ${JSON.stringify(TOAST_TITLE)}, ${JSON.stringify(TOAST_DETAIL)}),
    },
    "raise a two-line toast",
  );

export default {
  pages: (ctx) => {
    remember(ctx);
    return [
      { id: "wide", title: ${JSON.stringify(PAGE_TITLE)}, icon: "Puzzle", render: WidePage,
        nav: { label: "Wide page", icon: "Puzzle" } },
    ];
  },
  panels: (ctx) => {
    remember(ctx);
    return [
      { id: "2fa", title: ${JSON.stringify(PANEL_TITLE)}, icon: "Puzzle", render: TwoFactor,
        nav: { label: "Two factor", icon: "Puzzle" } },
    ];
  },
};
`;

const installRulesPlugin = (pluginsDir: string): void => {
  const target = NodePath.join(pluginsDir, RULES_ID);
  NodeFS.rmSync(target, { recursive: true, force: true });
  NodeFS.mkdirSync(NodePath.join(target, "web"), { recursive: true });
  NodeFS.writeFileSync(
    NodePath.join(target, "plugin.json"),
    `${JSON.stringify(RULES_MANIFEST, null, 2)}\n`,
  );
  NodeFS.writeFileSync(NodePath.join(target, "web", "index.mjs"), RULES_WEB_ENTRY);
};

/** What CSS does with an element: whether it truncates and whether the text overflows its box. */
const truncationOf = (page: Page, testId: string) =>
  page.getByTestId(testId).evaluate((element) => {
    const style = window.getComputedStyle(element);
    return {
      text: element.textContent ?? "",
      overflow: style.overflow,
      textOverflow: style.textOverflow,
      whiteSpace: style.whiteSpace,
    };
  });

test.describe("plugins — the host's checks at their S111 edges", () => {
  let running: PluginsHarnessState;

  test.beforeAll(async () => {
    test.setTimeout(240_000);
    running = state();
    await stopPluginsApp(running);
    installRulesPlugin(running.pluginsDir);
    running = await restartPluginsApp(running);
  });

  test.afterAll(async () => {
    // Registered, not written at the end of a case: the specs after this file share the tree, and
    // a failed assertion must not leave them a plugin nobody built (S15 C1).
    running = state();
    await stopPluginsApp(running);
    removePluginFolder(running.pluginsDir, RULES_ID);
    await restartPluginsApp(running);
  });

  test("S111 #2: a page titled with 100 characters is kept — its entry navigates, the header draws it truncated", async ({
    page,
  }) => {
    test.setTimeout(180_000);
    await openChat(page);
    const entry = page.getByRole("button", { name: "Wide page", exact: true }).first();
    await expect(entry, "the page's footer entry").toBeVisible({ timeout: 30_000 });
    await entry.dispatchEvent("click", { timeout: 15_000 });
    await expect(page).toHaveURL(new RegExp(`/plugins/${RULES_ID}/wide`), { timeout: 30_000 });
    await expect(page.getByTestId("host-rules-page")).toBeVisible({ timeout: 30_000 });
    const title = await truncationOf(page, "plugin-page-title");
    expect(title.text, "the header draws the WHOLE title").toBe(PAGE_TITLE);
    expect(
      [title.overflow, title.textOverflow, title.whiteSpace],
      "…and CSS truncates it (`truncate`), the draw site's own rule",
    ).toEqual(["hidden", "ellipsis", "nowrap"]);
    await saveEvidenceScreenshot(page, "s111-page-title-100");
  });

  test("S111 #1, #2, #8: the `2fa` panel with a 100-char title is shown and opens; its multi-line toast is shown", async ({
    page,
  }) => {
    test.setTimeout(180_000);
    await openChat(page);
    // A global-slot panel's footer button is labelled with the panel's TITLE.
    const button = page.getByRole("button", { name: PANEL_TITLE, exact: true }).first();
    await expect(
      button,
      "the `2fa` panel's footer button, labelled with its 100-char title",
    ).toBeVisible({
      timeout: 30_000,
    });
    await button.dispatchEvent("click", { timeout: 15_000 });
    const raise = page.getByTestId("host-rules-toast");
    await expect(raise, "the `2fa` panel is OPEN in the global slot").toBeVisible({
      timeout: 30_000,
    });

    await raise.click();
    // The app's toast (`components/ui/toast.tsx`): `toast-title` and `toast-description` slots.
    const title = page.locator('[data-slot="toast-title"]').filter({ hasText: TOAST_TITLE });
    await expect(title, "the plugin's toast is shown").toBeVisible({ timeout: 30_000 });
    const detail = page
      .locator('[data-slot="toast-description"]')
      .filter({ hasText: "second line of the detail" });
    await expect(detail, "…with its multi-line detail").toBeVisible();
    await expect(detail).toContainText("first line of the detail");
    await saveEvidenceScreenshot(page, "s111-2fa-panel-and-toast");
  });
});
