// ru-code S28 (V2-35), S37 — `ctx.invoke` readiness and the `transport` reason, in a real browser.
//
// THE CLAIM. A plugin's `ctx.invoke` never fails for a reason the plugin cannot see:
//   (a) a call made BEFORE the app's socket is up is PARKED by the host and sent, once, when the
//       session becomes live — no retry, no timer, exactly one frame on the wire;
//   (b) a call whose socket closes while it is IN FLIGHT rejects with
//       `PluginRpcError{reason:"transport"}` — not `plugin-failed` — and is NOT sent again.
//
// S37 deleted the third case. It armed a `send` that THREW the WebSocket standard's
// `InvalidStateError`, which a browser raises only for a socket that is not OPEN — and the app's
// transport writes under an open latch, so nothing but that hook could ever produce it (rule 36).
// The host's "one re-dispatch" answered an injected fault and is gone with it; `plugin.invoke` may
// have written to a plugin's own database and the contract carries no idempotency key, so a call
// that LEFT is now never sent twice.
//
// THE FIXTURE. The shipped demo gates its first `notes.list` on `ctx.connection === "ready"`, so it
// never calls before the socket is up. This spec therefore installs a COPY of the demo's built
// folder under a second id (`demo-early`: same server half, same methods, its own sqlite) with a
// tiny web entry of its own: a `background` component that calls `ctx.invoke("projects.count")`
// the moment it mounts — which is `loadPlugins()`, before the socket is chosen — and again on a
// `window` event the spec dispatches, writing every outcome into a `data-testid` the spec reads.
//
// THE TRANSPORT CONTROLS, both real. (a) takes the browser OFFLINE (`context.setOffline`): the open
// socket closes, the app's supervisor drops its session and goes to `offline`/`backoff`, and a call
// the plugin makes then has no live session to be sent on — until the browser is back online and
// the app reconnects by itself. (b) writes the frame and then CLOSES that socket (`socket.close()`,
// the same thing a dropped network does): the request really left and its answer can never arrive.
// The `WebSocket.prototype.send` hook (rules §4.24) is an OBSERVER — it counts frames and picks
// the moment to close — and never swallows or fails a write. `routeWebSocket` is deliberately not
// used: it replaces the page's `WebSocket` class, which would race the same hook.
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";

import { expect, openChat, state, test, type Page } from "./fixtures.ts";
import {
  DEMO_PLUGIN_DIST,
  removePluginFolder,
  restartPluginsApp,
  stopPluginsApp,
  type PluginsHarnessState,
} from "../harness/pluginsBoot.ts";
import { saveEvidenceJson } from "../harness/pluginsEvidence.ts";

const EARLY_ID = "demo-early";

const EARLY_WEB_ENTRY = `// e2e fixture (generated by invokeReadiness.e2e.test.ts): invoke at mount, and on demand.
import { createElement, useEffect, useState } from "react";

let ctxRef = null;

const outcomeOf = (call) =>
  call.then(
    (value) => "ok:" + String(value),
    (error) => "err:" + String(error && error.reason) + ":" + String(error && error.detail),
  );

function EarlyInvoke() {
  const [first, setFirst] = useState("pending");
  const [second, setSecond] = useState("idle");
  const [connection, setConnection] = useState(() => ctxRef.connection.get());
  useEffect(() => {
    // ctx.connection, straight off the signal (S28 step 4: truthful, not a lagging projection).
    const unsubscribe = ctxRef.connection.subscribe(() => setConnection(ctxRef.connection.get()));
    // At mount — which is loadPlugins(), before the socket is chosen on a cold load: the host
    // must park this, not refuse it.
    outcomeOf(ctxRef.invoke("projects.count")).then(setFirst);
    // (b) on demand: the spec drops the socket underneath this one.
    const onDemand = () => {
      setSecond("pending");
      outcomeOf(ctxRef.invoke("projects.count")).then(setSecond);
    };
    window.addEventListener("ru-e2e-early-invoke", onDemand);
    return () => {
      unsubscribe();
      window.removeEventListener("ru-e2e-early-invoke", onDemand);
    };
  }, []);
  return createElement(
    "span",
    {
      "data-testid": "early-invoke",
      "data-first": first,
      "data-second": second,
      "data-connection": connection,
      hidden: true,
    },
    first + " / " + second + " / " + connection,
  );
}

export default {
  background: (ctx) => {
    ctxRef = ctx;
    return [EarlyInvoke];
  },
};
`;

/** Copy the demo's built folder under a second id, with the fixture's own web half. */
const installEarlyPlugin = (pluginsDir: string): void => {
  const target = NodePath.join(pluginsDir, EARLY_ID);
  NodeFS.rmSync(target, { recursive: true, force: true });
  NodeFS.cpSync(DEMO_PLUGIN_DIST, target, { recursive: true });
  const manifest = JSON.parse(
    NodeFS.readFileSync(NodePath.join(target, "plugin.json"), "utf8"),
  ) as Record<string, unknown>;
  NodeFS.writeFileSync(
    NodePath.join(target, "plugin.json"),
    `${JSON.stringify({ ...manifest, id: EARLY_ID, name: "Early Plugin", styles: undefined }, null, 2)}\n`,
  );
  NodeFS.rmSync(NodePath.join(target, "web", "styles.css"), { force: true });
  NodeFS.writeFileSync(NodePath.join(target, "web", "index.mjs"), EARLY_WEB_ENTRY);
};

/**
 * Count every `plugin.invoke` frame for the fixture, and — when armed — close the socket the
 * moment after one of them has been WRITTEN.
 *
 * The hook never swallows and never throws: `nativeSend` always runs, so `attempts === sent` and
 * every frame this spec talks about really went out. `closeNext` then closes that socket, which is
 * what a dropped network does to a request whose answer has not come back yet.
 */
const WS_INIT = `
globalThis.__early = { attempts: 0, sent: 0, closeNext: false, closedUnder: 0, frames: [], sockets: 0 };
const WS = globalThis.WebSocket;
const nativeSend = WS.prototype.send;
const seqOf = (socket) => {
  if (socket.__earlySeq === undefined) socket.__earlySeq = globalThis.__early.sockets++;
  return socket.__earlySeq;
};
WS.prototype.send = function (data) {
  const text = typeof data === "string" ? data : "";
  if (!/"pluginId":"demo-early"/.test(text)) return nativeSend.call(this, data);
  const id = /"id":"?(\\d+)/.exec(text);
  const frame = { at: Date.now(), id: id === null ? "" : id[1], socket: seqOf(this), closedUnder: false };
  globalThis.__early.attempts += 1;
  globalThis.__early.sent += 1;
  const result = nativeSend.call(this, data);
  if (globalThis.__early.closeNext) {
    globalThis.__early.closeNext = false;
    globalThis.__early.closedUnder += 1;
    frame.closedUnder = true;
    // The frame LEFT; the socket goes away before its answer can come back.
    this.close(4000, "e2e: the connection dropped under an in-flight call");
  }
  globalThis.__early.frames.push(frame);
  return result;
};
`;

interface Wire {
  readonly attempts: number;
  readonly sent: number;
  readonly closedUnder: number;
  readonly frames: ReadonlyArray<{
    readonly at: number;
    readonly id: string;
    readonly socket: number;
    readonly closedUnder: boolean;
  }>;
}
const wire = (page: Page): Promise<Wire> =>
  page.evaluate(() => (globalThis as unknown as { __early: Wire }).__early);

const outcome = (page: Page) => page.locator('[data-testid="early-invoke"]');

test.describe("plugins — `ctx.invoke` readiness and the `transport` reason (S28, V2-35)", () => {
  let running: PluginsHarnessState;

  test.beforeAll(async () => {
    test.setTimeout(240_000);
    running = state();
    await stopPluginsApp(running);
    installEarlyPlugin(running.pluginsDir);
    running = await restartPluginsApp(running);
  });

  test.afterAll(async () => {
    running = state();
    await stopPluginsApp(running);
    removePluginFolder(running.pluginsDir, EARLY_ID);
    await restartPluginsApp(running);
  });

  test("(a) a call made with NO live session is PARKED and sent once the session is back — one frame", async ({
    page,
  }) => {
    test.setTimeout(180_000);
    await page.addInitScript(WS_INIT);
    await openChat(page);
    // The mount-time call (made during `loadPlugins()`, before any socket is chosen on a cold
    // load) resolved — parked or not, never refused.
    await expect(outcome(page), "the fixture's background mounted").toBeAttached({
      timeout: 60_000,
    });
    await expect(outcome(page)).toHaveAttribute("data-first", /^ok:\d+$/, { timeout: 60_000 });
    await expect(outcome(page)).toHaveAttribute("data-connection", "ready", { timeout: 30_000 });
    const settled = await wire(page);
    // S33 A4: the background component mounted ONCE — one mount-time frame, not one per plugin
    // that loaded around it (S28 §4.3 measured three: ids 4/5/6, one millisecond apart).
    expect(
      settled.attempts,
      `exactly one mount-time invoke — frames: ${JSON.stringify(settled.frames)}`,
    ).toBe(1);

    // Take the transport away: the socket closes, the supervisor drops its session, and the
    // plugin's signal says so — from the source, not a commit later.
    await page.context().setOffline(true);
    await expect(outcome(page), "`ctx.connection` reads the loss").toHaveAttribute(
      "data-connection",
      /^(lost|connecting)$/,
      { timeout: 30_000 },
    );
    await page.evaluate(() => window.dispatchEvent(new Event("ru-e2e-early-invoke")));
    await expect(outcome(page)).toHaveAttribute("data-second", "pending");
    await page.waitForTimeout(2_000);
    const parked = await wire(page);
    expect(parked.attempts, "nothing was sent while there was no session").toBe(settled.attempts);
    await expect(outcome(page), "…and the call is still parked, not refused").toHaveAttribute(
      "data-second",
      "pending",
    );

    // Give the transport back: the app reconnects on its own and the parked call goes out —
    // exactly ONE frame, and it resolves.
    await page.context().setOffline(false);
    await expect(outcome(page), "the parked call resolved after reconnect").toHaveAttribute(
      "data-second",
      /^ok:\d+$/,
      { timeout: 90_000 },
    );
    await expect(outcome(page)).toHaveAttribute("data-connection", "ready", { timeout: 30_000 });
    const after = await wire(page);
    expect(after.attempts - settled.attempts, "exactly one attempt for the parked call").toBe(1);
    expect(after.sent - settled.sent, "exactly one frame reached the wire").toBe(1);
    saveEvidenceJson("28-invoke-parked-offline", {
      spec: "invokeReadiness.e2e.test.ts",
      settled,
      parked,
      after,
      outcome: await outcome(page).getAttribute("data-second"),
    });
  });

  test("(b) a socket CLOSED under an in-flight call rejects with `transport`, and is not re-sent", async ({
    page,
  }) => {
    test.setTimeout(180_000);
    await page.addInitScript(WS_INIT);
    await openChat(page);
    await expect(outcome(page)).toHaveAttribute("data-first", /^ok:\d+$/, { timeout: 60_000 });
    const baseline = await wire(page);

    // Arm the close, then ask the plugin for a second call. The frame is written and the socket
    // that carried it is closed the instant after — a real drop with the request in flight.
    await page.evaluate(() => {
      (globalThis as unknown as { __early: { closeNext: boolean } }).__early.closeNext = true;
      window.dispatchEvent(new Event("ru-e2e-early-invoke"));
    });
    await expect(outcome(page), "the plugin was told `transport`").toHaveAttribute(
      "data-second",
      /^err:transport:/,
      { timeout: 60_000 },
    );
    const frames = await wire(page);
    const since = frames.frames.slice(baseline.frames.length);
    expect(frames.closedUnder, "exactly one socket closed under a frame").toBe(1);
    expect(frames.attempts, "every frame this spec counted really left").toBe(frames.sent);
    expect(
      since,
      `ONE frame, the one the socket closed under — frames since arming: ${JSON.stringify(since)}; before: ${JSON.stringify(baseline.frames)}`,
    ).toHaveLength(1);
    const second = await outcome(page).getAttribute("data-second");
    expect(second, "never the handler's reason").not.toMatch(/plugin-failed/);

    // The app reconnects on its own; a later call goes through again and the first is still good.
    await page.evaluate(() => window.dispatchEvent(new Event("ru-e2e-early-invoke")));
    await expect(outcome(page), "the next call, on the reconnected session").toHaveAttribute(
      "data-second",
      /^ok:\d+$/,
      { timeout: 90_000 },
    );
    const recovered = await wire(page);
    expect(
      recovered.frames.slice(frames.frames.length),
      "the recovery is ONE new frame, not a re-send plus a new one",
    ).toHaveLength(1);
    saveEvidenceJson("28-invoke-transport-mid-call", {
      spec: "invokeReadiness.e2e.test.ts",
      frames,
      second,
      recovered: await outcome(page).getAttribute("data-second"),
      framesAfterRecovery: recovered.frames.slice(frames.frames.length),
    });
  });
});
