// ru-code S26 (A1 + A3) — `Panel.description` at its two edges, in a real browser.
//
// THE CLAIM. The one line under a tab-mounted panel's launcher card and "+" menu entry is the
// plugin's own `Panel.description` (S22), and the host holds it to two rules the unit suite cannot
// see: (A1) an EMPTY description is "none" — the panel is kept and the card simply has no second
// line, exactly as if the field were omitted — and (A3) a description is CLAMPED where it is drawn
// (two lines under the card, one truncated line in the "+" menu), so a long one cannot push the
// app's own six cards out of the thread panel or turn the "+" popup into a wall of text.
//
// S41 item 2 (owner): the host does not INSPECT the field. Whatever the plugin wrote is drawn,
// trimmed and cut at 1000 characters; the third case below is a description with a newline in it,
// which is drawn like any other and reported to nobody.
//
// WHY A GENERATED FIXTURE. The shipped demo describes its tab in one honest sentence, and a real
// plugin with a 900-character description would be a bad plugin. The two edges need a plugin
// whose whole point is to sit on them, so it is written here — like `demo-named`, `flood` and
// `faulty` in the harness — with two tab panels, one per edge, and removed after the file.
//
// The S26 A5 half of the same audit (the "+" entry's reason off a thread) is proved in
// `apps/web/src/ru-code/tests/plugins/tabSurfaces.test.ts`: the only screen that draws the "+"
// menu without a thread is `/pull-requests` with a pull-request surface open, which needs a
// GitHub repository this harness does not have.
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";

import { expect, openChat, state, test, type Page } from "./fixtures.ts";
import {
  removePluginFolder,
  restartPluginsApp,
  stopPluginsApp,
  type PluginsHarnessState,
} from "../harness/pluginsBoot.ts";
import { saveEvidenceJson, saveEvidenceScreenshot } from "../harness/pluginsEvidence.ts";

const DESCRIBED_ID = "demo-described";
/** 900 characters — legal under `MAX_DESCRIPTION_LENGTH` (1000), and far more than a card can show. */
const LONG_DESCRIPTION = "lorem ipsum ".repeat(75).trim();
const BLANK_TAB_LABEL = /^Blank Tab$/;
/** The most ordinary authoring accident — a description with a newline in it. Drawn as given. */
const TWO_LINE_DESCRIPTION = "Skills of this project\nand the profile";
/**
 * Anchored on the LABEL only, like `LONG_TAB_LABEL` below: since S41 item 2 this card HAS a second
 * line, so its accessible name is the label PLUS the description. `/^Two Line Tab$/` matching
 * nothing is itself the proof the line is drawn — it is what the pre-fix spec used.
 */
const TWO_LINE_TAB_LABEL = /^Two Line Tab(?= |$)/;
/** The long card's accessible name is its label PLUS the description; anchor the label only. */
const LONG_TAB_LABEL = /^Long Tab(?= |$)/;

const DESCRIBED_MANIFEST = {
  id: DESCRIBED_ID,
  name: "Described Plugin",
  version: "0.1.0",
  apiVersion: 2,
  web: "web/index.mjs",
};

const DESCRIBED_WEB_ENTRY = `// e2e fixture (generated by panelDescription.e2e.test.ts): two tab panels on the description's edges.
import { createElement } from "react";

const Body = (id) => () => createElement("div", { "data-testid": "described-" + id }, id);

export default {
  panels: () => [
    // S26 A1: the host itself mints "" for "no description" — it must read as NONE, not as invalid.
    { id: "blank", title: "Blank Tab", icon: "Puzzle", mount: "tab", description: "",
      render: Body("blank") },
    // S26 A3: legal under the cap, and clamped where it is drawn.
    { id: "long", title: "Long Tab", icon: "Puzzle", mount: "tab",
      description: ${JSON.stringify(LONG_DESCRIPTION)}, render: Body("long") },
    // S41 item 2: a newline in it — drawn like any other line (HTML flow collapses it), never a
    // reason to drop the line, the panel, or the user's persisted tab.
    { id: "twoline", title: "Two Line Tab", icon: "Puzzle", mount: "tab",
      description: ${JSON.stringify(TWO_LINE_DESCRIPTION)}, render: Body("twoline") },
  ],
};
`;

const installDescribedPlugin = (pluginsDir: string): void => {
  const target = NodePath.join(pluginsDir, DESCRIBED_ID);
  NodeFS.rmSync(target, { recursive: true, force: true });
  NodeFS.mkdirSync(NodePath.join(target, "web"), { recursive: true });
  NodeFS.writeFileSync(
    NodePath.join(target, "plugin.json"),
    `${JSON.stringify(DESCRIBED_MANIFEST, null, 2)}\n`,
  );
  NodeFS.writeFileSync(NodePath.join(target, "web", "index.mjs"), DESCRIBED_WEB_ENTRY);
};

// ── the same chrome helpers `pluginTabs.e2e.test.ts` uses, for the same reasons ──────────────

/** `RightPanelTabs.tsx` `RightPanelEmptyState` — the launcher, when the panel has no surfaces. */
const launcher = (page: Page) => page.locator("[data-surface-launcher-keys]");
const RIGHT_PANEL_TOGGLE = /^(Переключить правую панель|Toggle right panel)/;

const dismissToasts = async (page: Page): Promise<void> => {
  const closers = page.locator('[data-slot="toast-close"]');
  for (let guard = 0; guard < 6; guard += 1) {
    if ((await closers.count()) === 0) return;
    await closers
      .first()
      .dispatchEvent("click", { timeout: 15_000 })
      .catch(() => undefined);
    await page.waitForTimeout(300);
  }
};

const forgetOpenSurfaces = async (page: Page): Promise<void> => {
  await page.evaluate(() => {
    for (let index = window.localStorage.length - 1; index >= 0; index -= 1) {
      const key = window.localStorage.key(index);
      if (key !== null && key.includes("right-panel-state")) window.localStorage.removeItem(key);
    }
  });
};

const openPluginChat = async (page: Page): Promise<void> => {
  await openChat(page);
  await forgetOpenSurfaces(page);
  await openChat(page);
  await dismissToasts(page);
};

const openEmptyRightPanel = async (page: Page): Promise<void> => {
  if (
    await launcher(page)
      .isVisible()
      .catch(() => false)
  )
    return;
  const toggle = page.getByRole("button", { name: RIGHT_PANEL_TOGGLE }).first();
  await expect(toggle, "the app's right-panel toggle").toBeVisible({ timeout: 30_000 });
  await toggle.dispatchEvent("click", { timeout: 15_000 });
  await expect(launcher(page), "the launcher, with no surface open yet").toBeVisible({
    timeout: 30_000,
  });
};

const card = (page: Page, label: RegExp) =>
  launcher(page).getByRole("button", { name: label }).first();

/** The card's second line — `RightPanelTabs.tsx`, the tagged description span. */
const cardDescription = (page: Page, label: RegExp) =>
  card(page, label).locator("span.line-clamp-2").first();

/** What the browser does with a clamped / truncated element: its box, and whether it overflows. */
const overflowOf = (locator: ReturnType<typeof card>) =>
  locator.evaluate((element) => {
    const style = window.getComputedStyle(element);
    return {
      clientHeight: element.clientHeight,
      scrollHeight: element.scrollHeight,
      clientWidth: element.clientWidth,
      scrollWidth: element.scrollWidth,
      lineClamp: style.getPropertyValue("-webkit-line-clamp"),
      overflow: style.overflow,
      textOverflow: style.textOverflow,
      whiteSpace: style.whiteSpace,
      lineHeight: Number.parseFloat(style.lineHeight),
    };
  });

test.describe("plugins — `Panel.description` at its edges (S26 A1, A3; S41 item 2)", () => {
  let running: PluginsHarnessState;

  test.beforeAll(async () => {
    test.setTimeout(240_000);
    running = state();
    await stopPluginsApp(running);
    installDescribedPlugin(running.pluginsDir);
    running = await restartPluginsApp(running);
  });

  test.afterAll(async () => {
    // Registered, not written at the end of a case: five specs run after this file on the same
    // tree, and a failed assertion must not leave them a plugin nobody built (S15 C1).
    running = state();
    await stopPluginsApp(running);
    removePluginFolder(running.pluginsDir, DESCRIBED_ID);
    await restartPluginsApp(running);
  });

  test('A1: a panel whose description is `""` is KEPT, and its card has no second line', async ({
    page,
  }) => {
    test.setTimeout(180_000);
    await openPluginChat(page);
    await openEmptyRightPanel(page);

    const blank = card(page, BLANK_TAB_LABEL);
    await expect(blank, "the blank-description card is on the launcher").toBeVisible({
      timeout: 30_000,
    });
    // The accessible name is EXACTLY the title (the regex is anchored) — no second line joined it —
    // and the card carries no description span at all.
    await expect(blank).toHaveText(/^\s*Blank Tab\s*$/);
    expect(await blank.locator("span.line-clamp-2").count(), "no second line").toBe(0);
    // …and the host raised no problem for this plugin: no toast names it.
    expect(
      await page
        .locator('[data-slot="toast-popup"]')
        .filter({ hasText: /demo-described|Described Plugin/ })
        .count(),
      "no problem toast for the described plugin",
    ).toBe(0);

    // Read BEFORE the click: the launcher unmounts when the tab opens, and `innerText()` on a
    // locator that matches nothing waits for the (unbounded) action timeout, not for an error.
    const cardText = await blank.innerText({ timeout: 5_000 });
    await saveEvidenceScreenshot(page, "plugin-description-blank");

    // The card is a real one: it opens the tab, inside the plugin's own root.
    await blank.dispatchEvent("click", { timeout: 15_000 });
    await expect(
      page.locator('[data-testid="described-blank"]'),
      "the blank tab's body",
    ).toBeVisible({ timeout: 30_000 });
    saveEvidenceJson("plugin-description-blank", {
      spec: "panelDescription.e2e.test.ts",
      cardText,
    });
  });

  test('A3: a 900-character description is CLAMPED on the card and TRUNCATED in the "+" menu', async ({
    page,
  }) => {
    test.setTimeout(180_000);
    await openPluginChat(page);
    await openEmptyRightPanel(page);

    // (a) the launcher card: two lines, no more — the description overflows its clamped box, and
    // the app's own cards are all still on screen under it.
    const long = card(page, LONG_TAB_LABEL);
    await expect(long, "the long-description card").toBeVisible({ timeout: 30_000 });
    const description = cardDescription(page, LONG_TAB_LABEL);
    await expect(description).toBeVisible();
    const cardBox = await overflowOf(description);
    expect(cardBox.lineClamp, "the card's second line is clamped").toBe("2");
    expect(cardBox.scrollHeight, "the description is longer than its box").toBeGreaterThan(
      cardBox.clientHeight,
    );
    expect(
      cardBox.clientHeight,
      `the box is at most two lines (${String(cardBox.clientHeight)} px at ${String(cardBox.lineHeight)} px/line)`,
    ).toBeLessThanOrEqual(Math.ceil(cardBox.lineHeight * 2) + 2);
    const agentsCard = launcher(page)
      .getByRole("button", { name: /^A (Agents|Агенты)(?= |$)/ })
      .first();
    await expect(agentsCard, "the app's LAST own card is still in the viewport").toBeInViewport();
    await saveEvidenceScreenshot(page, "plugin-description-clamp-card");

    // (b) the "+" menu entry: ONE line, truncated with an ellipsis, in a column no wider than the
    // menu's own text column.
    const filesCard = launcher(page)
      .getByRole("button", { name: /^F (Files|Файлы)(?= |$)/ })
      .first();
    await filesCard.dispatchEvent("click", { timeout: 15_000 });
    const plus = page.getByRole("button", { name: /^(Add panel surface|Добавить панель)/ }).first();
    await expect(plus, 'the strip\'s "+" button').toBeVisible({ timeout: 30_000 });
    await plus.dispatchEvent("click", { timeout: 15_000 });
    const menu = page.getByRole("menu").first();
    await expect(menu, 'the "+" menu').toBeVisible({ timeout: 15_000 });
    const entry = menu.getByRole("menuitem", { name: LONG_TAB_LABEL }).first();
    await expect(entry, "the long entry").toBeVisible();
    const entryDescription = entry.locator("span.truncate").last();
    const entryBox = await overflowOf(entryDescription);
    expect(entryBox.whiteSpace, "one line").toBe("nowrap");
    expect(entryBox.overflow, "hidden overflow").toBe("hidden");
    expect(entryBox.textOverflow, "an ellipsis").toBe("ellipsis");
    expect(entryBox.scrollWidth, "the text is wider than its box").toBeGreaterThan(
      entryBox.clientWidth,
    );
    expect(entryBox.clientWidth, "the column is bounded (`max-w-64` = 256 px)").toBeLessThanOrEqual(
      256,
    );
    const menuBox = await menu.boundingBox();
    expect(
      menuBox?.width ?? Number.POSITIVE_INFINITY,
      "the popup is not a wall of text",
    ).toBeLessThan(480);
    await saveEvidenceScreenshot(page, "plugin-description-truncate-menu");
    saveEvidenceJson("plugin-description-clamp", {
      spec: "panelDescription.e2e.test.ts",
      descriptionLength: LONG_DESCRIPTION.length,
      card: cardBox,
      menuEntry: entryBox,
      menuWidth: menuBox?.width ?? null,
    });
  });
  // MOVED at S41 item 2 (owner's ruling on S40 F5). This spec used to pin the S33 A3 rule — a
  // description with a control character in it is "undrawable", the host shows the card without a
  // second line and tells the author once through `seam:panels`. The host no longer inspects a
  // description at all: a `\n` is a typographic accident, not a broken contribution, and the same
  // judgement one seam over was dropping whole composer rows (and a `/` row's slug out of the
  // submit allowlist). So the claim is now the opposite and stronger: the line is DRAWN, the host
  // says NOTHING about it, and the persisted tab still survives — which is the half of S33 A3 that
  // was always the point.
  test("a multi-line description is DRAWN, unreported, and the persisted tab survives", async ({
    page,
  }) => {
    test.setTimeout(180_000);
    // V2-42 still binds: even now that there is nothing to report, nothing may ever slide in over
    // the app about a plugin. Both halves are asserted — no host line about this plugin's panels,
    // and no toast.
    const hostLines: string[] = [];
    page.on("console", (message) => {
      const text = message.text();
      if (text.startsWith("[plugins] ")) hostLines.push(text);
    });
    await page.addInitScript(() => {
      const log: string[] = [];
      (window as unknown as { __describedToasts: string[] }).__describedToasts = log;
      const scan = (): void => {
        const nodes = document.querySelectorAll(
          '[data-slot="toast-title"], [data-slot="toast-description"]',
        );
        for (const node of nodes) {
          const text = (node.textContent ?? "").trim();
          if (text.length === 0 || text.length > 400) continue;
          if (!/Described Plugin|description/.test(text)) continue;
          if (!log.includes(text)) log.push(text);
        }
      };
      new MutationObserver(scan).observe(document, {
        childList: true,
        subtree: true,
        characterData: true,
      });
      setInterval(scan, 100);
    });
    await openPluginChat(page);
    await openEmptyRightPanel(page);

    // The card HAS its second line now, and it is the plugin's own string — the newline is
    // collapsed by HTML flow, which is the whole reason it never needed refusing.
    const twoLine = card(page, TWO_LINE_TAB_LABEL);
    await expect(twoLine, "the two-line-description card is on the launcher").toBeVisible({
      timeout: 30_000,
    });
    // The pre-fix card had NO description span at all and an accessible name that was exactly the
    // title; both are now the opposite, which is the whole claim.
    const twoLineDescription = cardDescription(page, TWO_LINE_TAB_LABEL);
    await expect(twoLineDescription, "its second line").toBeVisible();
    await expect(twoLineDescription).toHaveText(/Skills of this project\s+and the profile/);
    expect(
      await launcher(page)
        .getByRole("button", { name: /^Two Line Tab$/ })
        .count(),
      "the card's accessible name is no longer just its title — the line joined it",
    ).toBe(0);
    // Read BEFORE the click, like the A1 case: the launcher unmounts when the tab opens, and
    // `innerText()` on a locator that matches nothing waits for the unbounded action timeout.
    const cardText = await twoLineDescription.innerText({ timeout: 5_000 });
    await saveEvidenceScreenshot(page, "plugin-description-multiline");

    // Scoped to THIS plugin, exactly as before: `demo-flood` contributes malformed panels, so
    // "how many seam:panels lines are there" is a question about the whole install.
    const describedLines = hostLines.filter((text) =>
      text.startsWith(`[plugins] ${DESCRIBED_ID} seam:panels`),
    );
    expect(describedLines, "the host says nothing about this plugin's panels").toEqual([]);
    const toasts = await page.evaluate(
      () => (window as unknown as { __describedToasts: string[] }).__describedToasts,
    );
    expect(toasts, "and the user was told nothing at all (V2-42)").toEqual([]);

    // The card opens the tab, inside the plugin's own root…
    await twoLine.dispatchEvent("click", { timeout: 15_000 });
    const body = page.locator('[data-testid="described-twoline"]');
    await expect(body, "the tab's body").toBeVisible({ timeout: 30_000 });

    // …and the tab is PERSISTED: a reload — where the seam is asked again and the reconcile runs
    // against the persisted right-panel state — brings the same tab back, still open.
    await page.reload({ waitUntil: "domcontentloaded" });
    await expect(body, "the tab survived the reload").toBeVisible({ timeout: 60_000 });
    // `pluginTabs.e2e.test.ts`: a tab in the strip is a button inside the tab list.
    const tab = page
      .locator("[data-right-panel-tab-list]")
      .getByRole("button", { name: /^Two Line Tab/ })
      .first();
    await expect(tab, "its tab is in the strip").toBeVisible({ timeout: 30_000 });
    saveEvidenceJson("plugin-description-multiline", {
      spec: "panelDescription.e2e.test.ts",
      description: TWO_LINE_DESCRIPTION,
      cardText,
      hostLines: describedLines,
      toasts,
      tabText: await tab.innerText({ timeout: 5_000 }),
    });
  });
});
