// ru-code S38 (V2-43) — Settings ▸ Plugins, end to end: the list, the switch, and the restart.
//
// THE CLAIM, in the order a user meets it:
//
//  1. the section lists every plugin the SERVER scanned — including the ones that did not load,
//     which since V2-42 is the only place their state is said at all;
//  2. a plugin that ships switched OFF (`"enabled": false`) is listed, off, and not running;
//  3. flipping a switch writes `<stateDir>/plugins/disabled.json` and says a restart is owed —
//     and nothing is torn down under the user: the plugin keeps running until then;
//  4. after a restart the server acts on the file, the row agrees, the sentence is gone, and the
//     plugin's surfaces are gone with it;
//  5. flipping the manifest-disabled one ON loads it after a restart — the user's answer beats the
//     manifest in both directions.
//
// IT RESTARTS THE SHARED APP, the way `uninstall.e2e.test.ts` does, and it puts everything back:
// the fixture folder is deleted, `disabled.json` is removed and the app is restarted once more in
// `afterAll`, so every spec that sorts after this one sees the plugin set it expects.
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";

import {
  restartPluginsApp,
  stopPluginsApp,
  writeHarnessPluginSwitches,
} from "../harness/pluginsBoot.ts";
import { saveEvidenceJson } from "../harness/pluginsEvidence.ts";

import { expect, state, test, type Page } from "./fixtures.ts";

/** A plugin whose MANIFEST ships it switched off — the V2-43 case, generated here. */
const SHIPPED_OFF_ID = "demo-shipped-off";
const SHIPPED_OFF_MANIFEST = {
  id: SHIPPED_OFF_ID,
  name: "Demo (shipped off)",
  version: "0.1.0",
  apiVersion: 2,
  enabled: false,
  web: "web/index.mjs",
};
const SHIPPED_OFF_WEB = `// e2e fixture (generated by pluginsSettings.e2e.test.ts): it must never run.
export default { panels: () => [{ id: "off", title: "Never", render: () => null }] };
`;

/** The plugin this spec switches off and on again. Its own specs sort before this file. */
const TOGGLED_ID = "analytics";

const SETTINGS_URL = (): string => `${state().webUrl}/settings/plugins`;
const PAGE = '[data-testid="plugins-settings-page"]';
const RESTART_LINE = '[data-testid="plugins-settings-restart"]';

const disabledFile = (): string =>
  NodePath.join(state().baseDir, "userdata", "plugins", "disabled.json");

const readSwitches = (): { disabled: string[]; enabled: string[] } => {
  const file = disabledFile();
  if (!NodeFS.existsSync(file)) return { disabled: [], enabled: [] };
  const parsed = JSON.parse(NodeFS.readFileSync(file, "utf8")) as {
    disabled?: string[];
    enabled?: string[];
  };
  return { disabled: parsed.disabled ?? [], enabled: parsed.enabled ?? [] };
};

const installShippedOff = (): void => {
  const dir = NodePath.join(state().pluginsDir, SHIPPED_OFF_ID);
  NodeFS.mkdirSync(NodePath.join(dir, "web"), { recursive: true });
  NodeFS.writeFileSync(
    NodePath.join(dir, "plugin.json"),
    `${JSON.stringify(SHIPPED_OFF_MANIFEST, null, 2)}\n`,
    "utf8",
  );
  NodeFS.writeFileSync(NodePath.join(dir, "web", "index.mjs"), SHIPPED_OFF_WEB, "utf8");
};

/** Stop the server, run `mutate` against the base dir, start it again on the same port. */
const restartWith = async (mutate: () => void): Promise<void> => {
  const running = state();
  await stopPluginsApp(running);
  mutate();
  await restartPluginsApp(running);
};

const openSettings = async (page: Page): Promise<void> => {
  await page.goto(SETTINGS_URL(), { waitUntil: "domcontentloaded" });
  await expect(page.locator(PAGE), "the Plugins settings section is on screen").toBeVisible({
    timeout: 60_000,
  });
};

/** One row's switch, by the plugin id the page tags it with. */
const rowSwitch = (page: Page, id: string) =>
  page.locator(`[data-testid="plugin-row-${id}"]`).getByRole("switch");

/** Open one row's collapsible body — where the root, the folder and the failure reason live. */
const expandRow = async (page: Page, id: string): Promise<void> => {
  await page
    .locator(`[data-testid="plugin-row-${id}"]`)
    .getByRole("button")
    .first()
    .dispatchEvent("click");
};

const rowState = async (page: Page, id: string): Promise<string> =>
  (await page
    .locator(`[data-testid="plugin-row-${id}"]`)
    .getAttribute("data-plugin-state")
    .catch(() => null)) ?? "absent";

test.describe("plugins — the Plugins settings section (V2-43)", () => {
  test.beforeAll(async () => {
    test.setTimeout(300_000);
    await restartWith(() => {
      installShippedOff();
    });
  });

  test.afterAll(async () => {
    test.setTimeout(300_000);
    await restartWith(() => {
      NodeFS.rmSync(NodePath.join(state().pluginsDir, SHIPPED_OFF_ID), {
        recursive: true,
        force: true,
      });
      // Back to the boot's switches, not to none: the harness enables auto-coder there (V2-43).
      NodeFS.rmSync(disabledFile(), { force: true });
      writeHarnessPluginSwitches(state().stateDir);
    });
  });

  test("lists every scanned plugin, and a manifest-disabled one is listed OFF", async ({
    page,
  }) => {
    test.setTimeout(300_000);
    await openSettings(page);

    // The harness's own plugins are all here, whatever state they reached.
    for (const id of ["demo", "catalogs", "analytics", "demo-broken", SHIPPED_OFF_ID]) {
      await expect(
        page.locator(`[data-testid="plugin-row-${id}"]`),
        `the section lists ${id}`,
      ).toBeVisible({ timeout: 30_000 });
    }

    // V2-43: shipped off means OFF and NOT RUNNING, and the dot says so without a word of text.
    await expect(rowSwitch(page, SHIPPED_OFF_ID)).not.toBeChecked();
    expect(await rowState(page, SHIPPED_OFF_ID)).toBe("skipped");
    await expect(
      page.locator(`[data-testid="plugin-dot-${SHIPPED_OFF_ID}"]`),
      "a skipped plugin's dot is grey — nothing ran and nothing is wrong",
    ).toHaveClass(/bg-muted-foreground/);
    await expect(
      page.locator(`[data-testid="plugin-dot-demo"]`),
      "a running plugin's dot is green",
    ).toHaveClass(/bg-success/);
    // S38 step 11: «работает»/"running" is gone — the dot carries it. What the BODY carries is the
    // root and the folder, and it is closed until the user asks.
    await expect(page.locator('[data-testid="plugins-settings-page"]')).not.toContainText(
      /running|работает/,
    );
    await expandRow(page, SHIPPED_OFF_ID);
    await expect(
      page.locator(`[data-testid="plugin-row-${SHIPPED_OFF_ID}"]`),
      "the body names the root and the folder",
    ).toContainText(/installed by you|установлен вами/);
    await expect(page.locator(`[data-testid="plugin-row-${SHIPPED_OFF_ID}"]`)).toContainText(
      SHIPPED_OFF_ID,
    );
    // S38 step 12.4: the body is composed the way the app's settings collapses are — one labelled
    // field per fact — and the FOLDER path wraps instead of being cut to one line (the owner saw
    // the cut). `break-all` is the wrap; `truncate` was the cut.
    await expect(
      page.locator(`[data-testid="plugin-row-${SHIPPED_OFF_ID}"]`),
      "each fact in the body is labelled",
    ).toContainText(/Folder|Папка/);
    await expect(
      page.locator(`[data-testid="plugin-row-${SHIPPED_OFF_ID}"] code`).last(),
      "the path wraps to a second line, it is never truncated",
    ).toHaveClass(/break-all/);

    // A healthy plugin is on, and nothing is owed yet.
    await expect(rowSwitch(page, "demo")).toBeChecked();
    expect(await rowState(page, "demo")).toBe("loaded");
    await expect(page.locator(RESTART_LINE), "nothing was switched, nothing to apply").toHaveCount(
      0,
    );

    saveEvidenceJson("38-plugins-settings-list", {
      spec: "pluginsSettings.e2e.test.ts",
      rows: await page.locator("[data-plugin-state]").evaluateAll((nodes) =>
        nodes.map((node) => ({
          id: node.getAttribute("data-testid"),
          state: node.getAttribute("data-plugin-state"),
        })),
      ),
    });
  });

  test("a switch is written and owed, and the restart is what makes it true", async ({ page }) => {
    test.setTimeout(600_000);
    await openSettings(page);

    // ── flip it OFF ─────────────────────────────────────────────────────────────────────────
    await rowSwitch(page, TOGGLED_ID).click();
    await expect(rowSwitch(page, TOGGLED_ID), "the switch reads SAVED, at once").not.toBeChecked();
    await expect(page.locator(RESTART_LINE), "…and the section says a restart is owed").toBeVisible(
      { timeout: 30_000 },
    );
    // Nothing was torn down: the plugin the user just switched off is still RUNNING.
    expect(await rowState(page, TOGGLED_ID)).toBe("loaded");
    await expect
      .poll(() => readSwitches().disabled, {
        timeout: 30_000,
        intervals: [500],
        message: "the file on disk carries the user's answer",
      })
      .toContain(TOGGLED_ID);

    // ── the restart is what acts on it ──────────────────────────────────────────────────────
    await restartWith(() => {});
    await openSettings(page);
    expect(await rowState(page, TOGGLED_ID), "the server skipped it this time").toBe("skipped");
    await expect(rowSwitch(page, TOGGLED_ID)).not.toBeChecked();
    await expect(
      page.locator(RESTART_LINE),
      "saved and running agree again, so the sentence is gone",
    ).toHaveCount(0);
    // …and its surfaces went with it: the page it contributed is not in the app any more.
    await page.goto(state().webUrl, { waitUntil: "domcontentloaded" });
    await expect(
      page.getByRole("button", { name: /^(Аналитика|Analytics)$/ }),
      "a switched-off plugin contributes nothing",
    ).toHaveCount(0, { timeout: 60_000 });

    // ── flip it back ON ─────────────────────────────────────────────────────────────────────
    await openSettings(page);
    await rowSwitch(page, TOGGLED_ID).click();
    await expect(rowSwitch(page, TOGGLED_ID)).toBeChecked();
    await expect(page.locator(RESTART_LINE)).toBeVisible({ timeout: 30_000 });
    await restartWith(() => {});
    await openSettings(page);
    expect(await rowState(page, TOGGLED_ID), "and it is back").toBe("loaded");
    await expect(page.locator(RESTART_LINE)).toHaveCount(0);
  });

  test("the user's ON beats a manifest that ships the plugin off", async ({ page }) => {
    test.setTimeout(600_000);
    await openSettings(page);

    await rowSwitch(page, SHIPPED_OFF_ID).click();
    await expect(rowSwitch(page, SHIPPED_OFF_ID)).toBeChecked();
    await expect
      .poll(() => readSwitches().enabled, {
        timeout: 30_000,
        intervals: [500],
        message: "the file records an explicit ENABLE, which is what beats the manifest",
      })
      .toContain(SHIPPED_OFF_ID);

    await restartWith(() => {});
    await openSettings(page);
    expect(
      await rowState(page, SHIPPED_OFF_ID),
      "a manifest-disabled plugin the user asked for LOADS",
    ).toBe("loaded");
    await expect(page.locator(RESTART_LINE)).toHaveCount(0);

    saveEvidenceJson("38-plugins-settings-switch", {
      spec: "pluginsSettings.e2e.test.ts",
      claim: "the user's switch is the answer for an id, in both directions (V2-43)",
      file: readSwitches(),
    });
  });

  // ru-code S38 step 11 — the two things the owner asked to be pinned in a browser.
  test("the notice survives navigation, and a toggle never remounts the row", async ({ page }) => {
    test.setTimeout(600_000);
    await openSettings(page);

    // THE ROW SURVIVES ITS OWN TOGGLE. The owner saw the list flicker; the rows are keyed by
    // plugin id and merged in place from the server's answer, so this is the same DOM element.
    const before = await page.locator(`[data-testid="plugin-row-${TOGGLED_ID}"]`).elementHandle();
    expect(before, "the row is on screen before the toggle").not.toBeNull();
    await rowSwitch(page, TOGGLED_ID).click();
    await expect(rowSwitch(page, TOGGLED_ID)).not.toBeChecked();
    const after = await page.locator(`[data-testid="plugin-row-${TOGGLED_ID}"]`).elementHandle();
    expect(
      await page.evaluate(([first, second]) => first === second, [before, after] as [
        Element | null,
        Element | null,
      ]),
      "the row is the SAME element before and after the switch — no remount, no flicker",
    ).toBe(true);

    // THE NOTICE PERSISTS ACROSS NAVIGATION: it is derived from what the SERVER says, not from a
    // local flag, so leaving the section and coming back does not clear it.
    await expect(page.locator(RESTART_LINE)).toBeVisible({ timeout: 30_000 });
    await page.goto(`${state().webUrl}/settings/general`, { waitUntil: "domcontentloaded" });
    await openSettings(page);
    await expect(
      page.locator(RESTART_LINE),
      "the notice is still there after navigating away and back",
    ).toBeVisible({ timeout: 30_000 });

    // …and the RESTART is what clears it.
    await restartWith(() => {});
    await openSettings(page);
    await expect(page.locator(RESTART_LINE)).toHaveCount(0);

    // Put the plugin back for whatever runs after this file.
    await rowSwitch(page, TOGGLED_ID).click();
    await expect(rowSwitch(page, TOGGLED_ID)).toBeChecked();
    await restartWith(() => {});
  });
});
