// ru-code: GENERATED by scripts/gen-host-modules.mjs — do not edit by hand.
// Host-provided module entry for "@base-ui/react/input" (D13). Its only job is to be a Rollup
// ENTRY that re-exports the app's own instance, so the emitted chunk shares the app's
// react/effect chunks and the import map can point "@base-ui/react/input" at it.

export * from "@base-ui/react/input";
