// ru-code: GENERATED by scripts/gen-host-modules.mjs — do not edit by hand.
// Host-provided module entry for "effect" (D13). Its only job is to be a Rollup
// ENTRY that re-exports the app's own instance, so the emitted chunk shares the app's
// react/effect chunks and the import map can point "effect" at it.

export * from "effect";
