// @ts-nocheck -- generated CJS re-export, see the note below
// ru-code: GENERATED by scripts/gen-host-modules.mjs — do not edit by hand.
// Host-provided module entry for "react-dom/client" (D13). Its only job is to be a Rollup
// ENTRY that re-exports the app's own instance, so the emitted chunk shares the app's
// react/effect chunks and the import map can point "react-dom/client" at it.

// "react-dom/client" is CommonJS: its named exports are the ones the bundler's interop
// synthesises, so they are listed explicitly — `export *` from CJS re-exports nothing
// (measured: the first build's `react` entry shipped only `default`).
export { createRoot, hydrateRoot, version } from "react-dom/client";
export { default } from "react-dom/client";
