// @ts-nocheck -- generated CJS re-export, see the note below
// ru-code: GENERATED by scripts/gen-host-modules.mjs — do not edit by hand.
// Host-provided module entry for "react-dom" (D13). Its only job is to be a Rollup
// ENTRY that re-exports the app's own instance, so the emitted chunk shares the app's
// react/effect chunks and the import map can point "react-dom" at it.

// "react-dom" is CommonJS: its named exports are the ones the bundler's interop
// synthesises, so they are listed explicitly — `export *` from CJS re-exports nothing
// (measured: the first build's `react` entry shipped only `default`).
export {
  __DOM_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE,
  createPortal,
  flushSync,
  preconnect,
  prefetchDNS,
  preinit,
  preinitModule,
  preload,
  preloadModule,
  requestFormReset,
  unstable_batchedUpdates,
  useFormState,
  useFormStatus,
  version,
} from "react-dom";
export { default } from "react-dom";
